### ISSUE TITLE
Refactor for testability

### ISSUE THREAD

**Issue by dngrhm** [walktalkchalk/TabStache#21]
I'd love a PR to refactor the code a bit to make the code more readable and testable.  Moving chrome extension functionality out of the event handler and calling those functions might be a good place to start.

**Comment by btruhand** [comment]
@dngrhm hi, I'd like to try taking this on

**Comment by dngrhm** [comment]
Awesome! Thanks for the interest!  Submit a PR and I'll take a gander.
